-- +goose Up 
-- +goose StatementBegin 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('EU','Europe','Andorra','AD','Andorra la Vella',270,595,1851); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('AS','Asia','United Arab Emirates','AE','Abu Dhabi',170,769,1799); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('AS','Asia','Afghanistan','AF','Kabul',22,662,2317); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('NA','North America','Antigua and Barbuda','AG','Saint Johns',443,534,1886); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('NA','North America','Anguilla','AI','The Valley',130,825,2202); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('EU','Europe','Albania','AL','Tirana',341,572,2749); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('AS','Asia','Armenia','AM','Yerevan',375,520,2284); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('AF','Africa','Angola','AO','Luanda',425,629,1687); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('AN','Antarctica','Antarctica','AQ','',490,609,1517); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('SA','South America','Argentina','AR','Buenos Aires',364,575,1912); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('OC','Oceania','American Samoa','AS','Pago Pago',253,647,2788); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('EU','Europe','Austria','AT','Vienna',175,820,2558); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('OC','Oceania','Australia','AU','Canberra',200,983,2870); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('NA','North America','Aruba','AW','Oranjestad',262,940,2432); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('EU','Europe','Åland','AX','Mariehamn',124,646,2206); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('AS','Asia','Azerbaijan','AZ','Baku',195,882,2067); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('EU','Europe','Bosnia and Herzegovina','BA','Sarajevo',291,795,2516); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('NA','North America','Barbados','BB','Bridgetown',196,646,2278); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('AS','Asia','Bangladesh','BD','Dhaka',114,856,2329); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('EU','Europe','Belgium','BE','Brussels',318,650,2219); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('AF','Africa','Burkina Faso','BF','Ouagadougou',399,916,1630); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('EU','Europe','Bulgaria','BG','Sofia',136,998,1505); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('AS','Asia','Bahrain','BH','Manama',221,567,2075); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('AF','Africa','Burundi','BI','Bujumbura',235,502,1830); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('AF','Africa','Benin','BJ','Porto-Novo',436,542,1978); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('NA','North America','Saint Barthélemy','BL','Gustavia',197,936,2318); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('NA','North America','Bermuda','BM','Hamilton',368,903,2750); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('AS','Asia','Brunei','BN','Bandar Seri Begawan',459,595,2180); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('SA','South America','Bolivia','BO','Sucre',377,810,2506); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('NA','North America','Bonaire','BQ','Kralendijk',90,549,2508); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('SA','South America','Brazil','BR','Brasília',39,714,2289); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('NA','North America','Bahamas','BS','Nassau',253,871,1599); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('AS','Asia','Bhutan','BT','Thimphu',353,701,1525); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('AN','Antarctica','Bouvet Island','BV','',152,947,2780); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('AF','Africa','Botswana','BW','Gaborone',263,692,1640); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('EU','Europe','Belarus','BY','Minsk',453,826,2862); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('NA','North America','Belize','BZ','Belmopan',52,744,2544); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('NA','North America','Canada','CA','Ottawa',418,908,2984); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('AS','Asia','Cocos [Keeling] Islands','CC','West Island',300,590,1959); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('AF','Africa','Democratic Republic of the Congo','CD','Kinshasa',19,845,1614); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('AF','Africa','Central African Republic','CF','Bangui',478,595,1599); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('AF','Africa','Republic of the Congo','CG','Brazzaville',155,541,2331); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('EU','Europe','Switzerland','CH','Bern',287,704,2990); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('AF','Africa','Ivory Coast','CI','Yamoussoukro',162,607,2319); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('OC','Oceania','Cook Islands','CK','Avarua',339,869,2336); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('SA','South America','Chile','CL','Santiago',5,947,2708); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('AF','Africa','Cameroon','CM','Yaoundé',342,977,2283); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('AS','Asia','China','CN','Beijing',210,609,2118); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('SA','South America','Colombia','CO','Bogotá',243,799,1640); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('NA','North America','Costa Rica','CR','San José',216,866,2462); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('NA','North America','Cuba','CU','Havana',333,855,2081); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('AF','Africa','Cape Verde','CV','Praia',405,712,2673); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('NA','North America','Curacao','CW','Willemstad',261,839,2287); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('AS','Asia','Christmas Island','CX','Flying Fish Cove',57,900,2922); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('EU','Europe','Cyprus','CY','Nicosia',178,860,1529); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('EU','Europe','Czech Republic','CZ','Prague',12,849,1599); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('EU','Europe','Germany','DE','Berlin',26,500,1719); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('AF','Africa','Djibouti','DJ','Djibouti',469,616,1701); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('EU','Europe','Denmark','DK','Copenhagen',45,916,1519); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('NA','North America','Dominica','DM','Roseau',184,741,2201); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('NA','North America','Dominican Republic','DO','Santo Domingo',462,646,2278); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('AF','Africa','Algeria','DZ','Algiers',483,929,2925); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('SA','South America','Ecuador','EC','Quito',133,797,2179); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('EU','Europe','Estonia','EE','Tallinn',95,983,2055); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('AF','Africa','Egypt','EG','Cairo',296,789,2140); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('AF','Africa','Western Sahara','EH','El Aaiún',1,638,2634); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('AF','Africa','Eritrea','ER','Asmara',19,838,2264); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('EU','Europe','Spain','ES','Madrid',301,943,2021); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('AF','Africa','Ethiopia','ET','Addis Ababa',180,503,1596); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('EU','Europe','Finland','FI','Helsinki',402,761,1631); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('OC','Oceania','Fiji','FJ','Suva',198,949,2194); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('SA','South America','Falkland Islands','FK','Stanley',368,520,1900); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('OC','Oceania','Micronesia','FM','Palikir',263,723,2136); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('EU','Europe','Faroe Islands','FO','Tórshavn',90,855,2728); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('EU','Europe','France','FR','Paris',203,615,2558); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('AF','Africa','Gabon','GA','Libreville',194,976,1551); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('EU','Europe','United Kingdom','GB','London',13,702,2811); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('NA','North America','Grenada','GD','St. Georges',481,801,1754); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('AS','Asia','Georgia','GE','Tbilisi',183,932,1922); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('SA','South America','French Guiana','GF','Cayenne',94,626,2644); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('EU','Europe','Guernsey','GG','St. Peter Port',16,614,2441); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('AF','Africa','Ghana','GH','Accra',39,519,2540); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('EU','Europe','Gibraltar','GI','Gibraltar',83,707,1720); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('NA','North America','Greenland','GL','Nuuk',219,862,1555); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('AF','Africa','Gambia','GM','Banjul',363,652,2774); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('AF','Africa','Guinea','GN','Conakry',417,964,1595); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('NA','North America','Guadeloupe','GP','Basse-Terre',452,628,2977); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('AF','Africa','Equatorial Guinea','GQ','Malabo',234,855,2041); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('EU','Europe','Greece','GR','Athens',38,601,1965); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('AN','Antarctica','South Georgia and the South Sandwich Islands','GS','King Edward Point',304,687,2455); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('NA','North America','Guatemala','GT','Guatemala City',478,914,2715); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('OC','Oceania','Guam','GU','Hagåtña',329,608,2219); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('AF','Africa','Guinea-Bissau','GW','Bissau',297,547,1581); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('SA','South America','Guyana','GY','Georgetown',84,644,2684); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('AS','Asia','Hong Kong','HK','City of Victoria',442,850,1503); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('AN','Antarctica','Heard Island and McDonald Islands','HM','',345,686,2621); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('NA','North America','Honduras','HN','Tegucigalpa',476,667,1994); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('EU','Europe','Croatia','HR','Zagreb',317,897,1636); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('NA','North America','Haiti','HT','Port-au-Prince',222,513,2272); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('EU','Europe','Hungary','HU','Budapest',399,794,1565); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('AS','Asia','Indonesia','ID','Jakarta',63,963,2748); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('EU','Europe','Ireland','IE','Dublin',226,608,2104); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('AS','Asia','Israel','IL','Jerusalem',331,617,2105); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('EU','Europe','Isle of Man','IM','Douglas',28,894,2984); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('AS','Asia','India','IN','New Delhi',280,631,2701); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('AS','Asia','British Indian Ocean Territory','IO','Diego Garcia',82,505,2012); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('AS','Asia','Iraq','IQ','Baghdad',456,773,2505); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('AS','Asia','Iran','IR','Tehran',110,720,1549); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('EU','Europe','Iceland','IS','Reykjavik',139,796,1801); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('EU','Europe','Italy','IT','Rome',231,633,1686); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('EU','Europe','Jersey','JE','Saint Helier',183,677,2820); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('NA','North America','Jamaica','JM','Kingston',486,697,1620); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('AS','Asia','Jordan','JO','Amman',67,587,1795); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('AS','Asia','Japan','JP','Tokyo',494,559,2900); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('AF','Africa','Kenya','KE','Nairobi',212,749,2151); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('AS','Asia','Kyrgyzstan','KG','Bishkek',260,813,2066); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('AS','Asia','Cambodia','KH','Phnom Penh',461,904,2996); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('OC','Oceania','Kiribati','KI','South Tarawa',120,512,2312); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('AF','Africa','Comoros','KM','Moroni',401,509,2141); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('NA','North America','Saint Kitts and Nevis','KN','Basseterre',315,737,2374); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('AS','Asia','North Korea','KP','Pyongyang',265,990,2297); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('AS','Asia','South Korea','KR','Seoul',10,827,2191); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('AS','Asia','Kuwait','KW','Kuwait City',306,586,2964); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('NA','North America','Cayman Islands','KY','George Town',43,848,2818); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('AS','Asia','Kazakhstan','KZ','Astana',23,625,2916); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('AS','Asia','Laos','LA','Vientiane',21,827,2155); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('AS','Asia','Lebanon','LB','Beirut',277,555,2914); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('NA','North America','Saint Lucia','LC','Castries',100,516,1766); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('EU','Europe','Liechtenstein','LI','Vaduz',426,597,2325); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('AS','Asia','Sri Lanka','LK','Colombo',368,765,2793); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('AF','Africa','Liberia','LR','Monrovia',284,761,2980); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('AF','Africa','Lesotho','LS','Maseru',35,748,2487); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('EU','Europe','Lithuania','LT','Vilnius',330,861,2869); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('EU','Europe','Luxembourg','LU','Luxembourg',37,734,2052); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('EU','Europe','Latvia','LV','Riga',76,944,2192); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('AF','Africa','Libya','LY','Tripoli',420,733,2800); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('AF','Africa','Morocco','MA','Rabat',92,612,1627); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('EU','Europe','Monaco','MC','Monaco',419,530,2084); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('EU','Europe','Moldova','MD','Chișinău',71,795,1567); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('EU','Europe','Montenegro','ME','Podgorica',253,755,1740); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('NA','North America','Saint Martin','MF','Marigot',167,882,2345); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('AF','Africa','Madagascar','MG','Antananarivo',181,880,2411); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('OC','Oceania','Marshall Islands','MH','Majuro',272,798,2960); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('EU','Europe','North Macedonia','MK','Skopje',52,749,1654); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('AF','Africa','Mali','ML','Bamako',222,762,2998); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('AS','Asia','Myanmar [Burma]','MM','Naypyidaw',72,927,2818); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('AS','Asia','Mongolia','MN','Ulan Bator',167,971,2998); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('AS','Asia','Macao','MO','',166,730,1742); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('OC','Oceania','Northern Mariana Islands','MP','Saipan',312,533,1922); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('NA','North America','Martinique','MQ','Fort-de-France',171,823,1827); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('AF','Africa','Mauritania','MR','Nouakchott',110,738,2156); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('NA','North America','Montserrat','MS','Plymouth',148,605,1922); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('EU','Europe','Malta','MT','Valletta',307,544,1934); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('AF','Africa','Mauritius','MU','Port Louis',108,619,2468); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('AS','Asia','Maldives','MV','Malé',376,658,2067); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('AF','Africa','Malawi','MW','Lilongwe',230,644,2098); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('NA','North America','Mexico','MX','Mexico City',330,518,2434); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('AS','Asia','Malaysia','MY','Kuala Lumpur',453,733,2939); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('AF','Africa','Mozambique','MZ','Maputo',70,736,2889); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('AF','Africa','Namibia','NA','Windhoek',268,609,1579); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('OC','Oceania','New Caledonia','NC','Nouméa',191,906,2997); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('AF','Africa','Niger','NE','Niamey',318,611,2834); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('OC','Oceania','Norfolk Island','NF','Kingston',416,866,2740); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('AF','Africa','Nigeria','NG','Abuja',67,714,1950); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('NA','North America','Nicaragua','NI','Managua',123,829,1660); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('EU','Europe','Netherlands','NL','Amsterdam',166,965,1636); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('EU','Europe','Norway','NO','Oslo',148,630,2332); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('AS','Asia','Nepal','NP','Kathmandu',71,910,2303); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('OC','Oceania','Nauru','NR','Yaren',492,856,2781); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('OC','Oceania','Niue','NU','Alofi',254,694,2369); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('OC','Oceania','New Zealand','NZ','Wellington',260,642,2856); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('AS','Asia','Oman','OM','Muscat',332,972,1502); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('NA','North America','Panama','PA','Panama City',348,853,2210); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('SA','South America','Peru','PE','Lima',327,788,2455); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('OC','Oceania','French Polynesia','PF','Papeetē',235,566,2661); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('OC','Oceania','Papua New Guinea','PG','Port Moresby',456,956,1854); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('AS','Asia','Philippines','PH','Manila',178,516,2960); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('AS','Asia','Pakistan','PK','Islamabad',73,634,2674); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('EU','Europe','Poland','PL','Warsaw',366,624,2739); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('NA','North America','Saint Pierre and Miquelon','PM','Saint-Pierre',12,992,2293); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('OC','Oceania','Pitcairn Islands','PN','Adamstown',384,655,2217); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('NA','North America','Puerto Rico','PR','San Juan',22,790,1735); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('AS','Asia','Palestine','PS','Ramallah',60,543,2167); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('EU','Europe','Portugal','PT','Lisbon',499,875,2400); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('OC','Oceania','Palau','PW','Ngerulmud',127,682,2350); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('SA','South America','Paraguay','PY','Asunción',18,923,2380); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('AS','Asia','Qatar','QA','Doha',132,521,1844); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('AF','Africa','Réunion','RE','Saint-Denis',169,941,2324); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('EU','Europe','Romania','RO','Bucharest',146,868,2268); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('EU','Europe','Serbia','RS','Belgrade',27,736,2530); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('EU','Europe','Russia','RU','Moscow',218,651,1532); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('AF','Africa','Rwanda','RW','Kigali',410,774,1555); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('AS','Asia','Saudi Arabia','SA','Riyadh',177,943,1979); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('OC','Oceania','Solomon Islands','SB','Honiara',101,834,1894); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('AF','Africa','Seychelles','SC','Victoria',22,734,1603); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('AF','Africa','Sudan','SD','Khartoum',91,969,1997); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('EU','Europe','Sweden','SE','Stockholm',87,762,1690); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('AS','Asia','Singapore','SG','Singapore',444,689,2050); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('AF','Africa','Saint Helena','SH','Jamestown',307,845,1848); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('EU','Europe','Slovenia','SI','Ljubljana',182,859,2476); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('EU','Europe','Svalbard and Jan Mayen','SJ','Longyearbyen',294,952,2778); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('EU','Europe','Slovakia','SK','Bratislava',261,762,2469); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('AF','Africa','Sierra Leone','SL','Freetown',195,849,1516); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('EU','Europe','San Marino','SM','City of San Marino',85,808,2648); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('AF','Africa','Senegal','SN','Dakar',339,651,1619); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('AF','Africa','Somalia','SO','Mogadishu',258,812,2780); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('SA','South America','Suriname','SR','Paramaribo',339,629,2189); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('AF','Africa','South Sudan','SS','Juba',200,990,2529); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('AF','Africa','São Tomé and Príncipe','ST','São Tomé',307,569,1659); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('NA','North America','El Salvador','SV','San Salvador',389,892,2689); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('NA','North America','Sint Maarten','SX','Philipsburg',189,967,1505); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('AS','Asia','Syria','SY','Damascus',335,729,2112); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('AF','Africa','Swaziland','SZ','Lobamba',34,516,2953); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('NA','North America','Turks and Caicos Islands','TC','Cockburn Town',45,655,2454); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('AF','Africa','Chad','TD','NDjamena',314,767,2473); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('AN','Antarctica','French Southern Territories','TF','Port-aux-Français',493,972,2828); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('AF','Africa','Togo','TG','Lomé',28,508,2850); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('AS','Asia','Thailand','TH','Bangkok',357,911,2692); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('AS','Asia','Tajikistan','TJ','Dushanbe',470,845,2090); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('OC','Oceania','Tokelau','TK','Fakaofo',231,687,2256); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('OC','Oceania','East Timor','TL','Dili',218,649,2024); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('AS','Asia','Turkmenistan','TM','Ashgabat',8,883,2282); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('AF','Africa','Tunisia','TN','Tunis',129,966,2338); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('OC','Oceania','Tonga','TO','Nukualofa',191,637,1538); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('AS','Asia','Turkey','TR','Ankara',428,736,1927); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('NA','North America','Trinidad and Tobago','TT','Port of Spain',65,567,1821); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('OC','Oceania','Tuvalu','TV','Funafuti',426,915,2418); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('AS','Asia','Taiwan','TW','Taipei',182,953,2420); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('AF','Africa','Tanzania','TZ','Dodoma',411,850,1988); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('EU','Europe','Ukraine','UA','Kyiv',418,731,2158); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('AF','Africa','Uganda','UG','Kampala',174,773,2881); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('OC','Oceania','U.S. Minor Outlying Islands','UM','',291,629,1757); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('NA','North America','United States','US','Washington D.C.',192,980,2712); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('SA','South America','Uruguay','UY','Montevideo',468,723,1972); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('AS','Asia','Uzbekistan','UZ','Tashkent',181,967,1687); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('EU','Europe','Vatican City','VA','Vatican City',304,536,2810); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('NA','North America','Saint Vincent and the Grenadines','VC','Kingstown',254,675,2449); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('SA','South America','Venezuela','VE','Caracas',217,601,1632); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('NA','North America','British Virgin Islands','VG','Road Town',417,632,1549); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('NA','North America','U.S. Virgin Islands','VI','Charlotte Amalie',331,526,2291); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('AS','Asia','Vietnam','VN','Hanoi',341,507,1873); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('OC','Oceania','Vanuatu','VU','Port Vila',386,939,2979); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('OC','Oceania','Wallis and Futuna','WF','Mata-Utu',129,594,2129); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('OC','Oceania','Samoa','WS','Apia',472,875,1818); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('EU','Europe','Kosovo','XK','Pristina',246,985,2332); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('AS','Asia','Yemen','YE','Sanaa',307,575,1820); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('AF','Africa','Mayotte','YT','Mamoudzou',73,922,1760); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('AF','Africa','South Africa','ZA','Pretoria',322,544,2135); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('AF','Africa','Zambia','ZM','Lusaka',144,683,2941); 
INSERT INTO countries SET (continent_code,continent,country,country_code,capital,value_budget,value_midrange,value_luxury) VALUES ('AF','Africa','Zimbabwe','ZW','Harare',446,961,2151); 
-- +goose StatementEnd
      