version: '3'

volumes:
  postgres-data:
    driver: local

services:
  postgres:
    container_name: postgres
    image: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  countries-api:
    container_name: countries-api
    build: .
    ports:
      - 3030:3030
    environment:
      - PORT=3030
      - POSTGRES_DSN=postgres://postgres:postgres@postgres:5432/postgres?sslmode=disable
      - PROTO_PATH=/countries-api/pb/demo.proto
    depends_on:
      - postgres
